Upgrade bytes to 1.11.1
Update bytes to 1.11.1 to fix a security issue in BytesMut::reserve
(RUSTSEC-2026-0007) and unblock cargo audit.

Previously we got the following while running `cargo audit`:

```
Crate:     bytes
Version:   1.11.0
Title:     Integer overflow in `BytesMut::reserve`
Date:      2026-02-03
ID:        RUSTSEC-2026-0007
URL:       https://github.com/advisories/GHSA-434x-w66g-qw3r
error: 1 vulnerability found!
Solution:  Upgrade to >=1.11.1
```