Update time crate to 0.3.47.
`cargo audit` was failing with the following error:

```
Crate:     time
Version:   0.3.44
Title:     Impact
Date:      2026-02-05
error: 1 vulnerability found!
ID:        RUSTSEC-2026-0009
URL:       https://rustsec.org/advisories/RUSTSEC-2026-0009
Severity:  6.8 (medium)
Solution:  Upgrade to >=0.3.47
```

This commit fixes that by updating the time crate to 0.3.47.